{% set name = "odl" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/odlgroup/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f5db50a689e3081db8d08067137937c12aa429782917b071e24bd982dd3acbfb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=65.6

  run:
    - python >={{ python_min }}
    - setuptools <76.0
    - future >=0.16
    - numpy >=1.19, <1.27
    - scipy >=1.1
    - packaging >=17.0
    - matplotlib-base >=3.4

test:
  requires:
    - pytest >=5.4, <8.0
    - python {{ python_min }}
  imports:
    - odl
  commands:
    - python -c "import odl; odl.test()"

about:
  home: https://github.com/odlgroup/odl
  license: MPL-2.0
  license_file: LICENSE
  summary: "Operator Discretization Library - a versatile Python framework for rapid prototyping in Inverse Problems and related fields"
  doc_url: https://odlgroup.github.io/odl/
  dev_url: https://github.com/odlgroup/odl

extra:
  recipe-maintainers:
    # Ozan Öktem
    - ozanoktem
    # Justus Sagemüller
    - leftaroundabout
    # Emilien Valat
    - Emvlt
